FROM node:latest


WORKDIR /app


RUN apt-get update && apt-get install -y netcat-traditional curl


COPY package.json .
COPY yarn.lock .

RUN npm install

COPY . .


RUN chmod +x ./scripts/wait-for-it.sh





