FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf


COPY nginx.conf /etc/nginx/conf.d


RUN apt-get update && apt-get install -y netcat-traditional curl

COPY package.json .
COPY yarn.lock .

RUN npm install

COPY . .

COPY ./scripts/wait-for-it.sh /usr/local/bin/wait-for-it.sh
RUN chmod +x ./scripts/wait-for-it.sh

EXPOSE 3000

CMD ["/usr/local/bin/wait-for-it.sh","backend","npm","run","dev"]
