version: "3.8"
services:
  frontend:
    container_name: frontend
    build:
      context: "./frontend"

    environment:
      VITE_API_URL: "http://localhost:81/api"
      VITE_BACKEND_HOST: backend
      APP_PORT: "3000"

    ports:
      - "3001:3000"

    depends_on:
      - backend
      - proxy
    networks:
      - nt1
    volumes:
      - ./frontend:/app

  backend:
    container_name: backend
    build:
      context: "./backend"
      dockerfile: Dockerfile

    ports:
      - "8081:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/projeto_integrador_2
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db

    networks:
      - nt1
    volumes:
      - ./backend/target:/app

  db:
    container_name: db
    build:
      context: "./db"
      dockerfile: "Dockerfile"

    ports:
      - "5433:5432"

    environment:
      POSTGRES_DB: projeto_integrador_2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - nt1

  proxy:
    container_name: proxy
    build:
      context: "./proxy"
      dockerfile: "Dockerfile"

    ports:
      - "81:80"

    networks:
      - nt1

    depends_on:
      - backend

volumes:
  postgres-data:

networks:
  nt1:
    driver: bridge
