version: "3.8"
services:
  frontend:
    build:
      context: "./frontend"

    depends_on:
      - backend

  backend:
    build:
      context: "./backend"
      dockerfile: Dockerfile

    depends_on:
      - db

  db:
    build:
      context: "./db"

networks:
  nt1:
    driver: bridge
