version: "3.8"
services:
  frontend:
    build:
      context: "./frontend"

  backend:
    build:
      context: "./backend"
      dockerfile: Dockerfile

  db:
    build:
      context: "./db"

networks:
  nt1:
    driver: bridge
