FROM eclipse-temurin:21

WORKDIR /app

COPY /app/target/*.jar app.jar


COPY ./scripts/wait-for-it.sh /usr/local/bin/wait-for-it.sh

RUN chmod +x /usr/local/bin/wait-for-it.sh

EXPOSE 8080

CMD ["/usr/local/bin/wait-for-it.sh", "db:5432", "--","java","-jar","/app/app.jar"]

