FROM maven:3.8.7-eclipse-temurin-21 AS build

WORKDIR /app

COPY ./pom.xml .

RUN mvn dependency:go-offline

COPY src/ ./src

RUN mvn clean package -DskipTests

FROM eclipse-temurin:21

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar


COPY ./scripts/wait-for-it.sh /usr/local/bin/wait-for-it.sh

EXPOSE 8080

CMD ["/usr/local/bin/wait-for-it.sh", "db:5432", "--","java","-jar","/app/app.jar"]

